"""
ForceModel Model

This module defines a ForceModel model for database operations.
Generated by Fast Track Framework CLI.

Sprint 9.0: Uses SQLAlchemy 2.0 (Mapped, mapped_column).
"""

from sqlalchemy import String
from sqlalchemy.orm import Mapped, mapped_column

from fast_query import Base, SoftDeletesMixin, TimestampMixin


class ForceModel(Base, TimestampMixin, SoftDeletesMixin):
    """
    ForceModel model.
    
    This model includes automatic timestamp management (created_at, updated_at)
    and soft delete functionality (deleted_at).
    
    Sprint 9.0:
        - Uses SQLAlchemy 2.0 syntax (Mapped, mapped_column)
        - Compatible with Hybrid Repository (Sprint 8.0)
        - Type-safe with full MyPy support
    
    Attributes:
        id: Primary key
        name: ForceModel name
        # Add more fields as needed
    
    Example:
        >>> user = User(name="Alice", email="alice@example.com")
        >>> await repo.create(user)  # repo is HybridRepository
    """
    
    __tablename__ = "force_models"
    
    # Primary key
    id: Mapped[int] = mapped_column(primary_key=True)
    
    # Fields
    name: Mapped[str] = mapped_column(String(100))
    
    # TODO: Add more columns here
    # Example:
    # email: Mapped[str] = mapped_column(String(255), unique=True)
    # is_active: Mapped[bool] = mapped_column(default=True)
    
    # TODO: Define relationships here
    # Example:
    # posts: Mapped[list["Post"]] = relationship("Post", back_populates="user")
    
    def __repr__(self) -> str:
        """String representation for debugging."""
        return f"<ForceModel(id={self.id}, name={self.name})>"
    