"""
TestRepository

This module defines a repository for Test operations.
Generated by Fast Track Framework CLI.

Sprint 9.0: Uses Hybrid Repository pattern (Sprint 8.0) with Container DI.
"""

from sqlalchemy.ext.asyncio import AsyncSession

from fast_query import BaseRepository
from app.models import Test


class TestRepository(BaseRepository[Test]):
    """
    Repository for Test database operations.
    
    Inherits from BaseRepository (Hybrid Pattern - Sprint 8.0):
    - Convenience methods: find(id), create(), update(), delete(), all(), etc.
    - Native session access: self.session.execute(select(...)) for advanced queries
    
    Sprint 9.0:
        - AsyncSession is injected via Container DI
        - Can use both convenience methods and native session
        - Supports CTEs, Window Functions, Bulk Operations
    
    Example usage:
        >>> # Use convenience methods (recommended for simple operations)
        >>> user = await repo.find(123)
        >>> 
        >>> # Use native session for advanced queries
        >>> from sqlalchemy import select
        >>> stmt = select(Test).where(...)
        >>> result = await repo.session.execute(stmt)
    
    Available methods:
    - find(id): Find by primary key
    - find_or_fail(id): Find or raise RecordNotFound
    - all(): Get all records
    - paginate(page, per_page): Paginated results
    - create(data): Create new record
    - update(id, data): Update existing record
    - delete(id): Delete record (soft delete if mixin enabled)
    - query(): Get QueryBuilder for fluent queries
    - session: Native AsyncSession access for advanced queries (CTEs, Window Functions)
    
    Add custom query methods here.
    
    Example:
        >>> async def find_by_email(self, email: str) -> Test | None:
        ...     stmt = select(Test).where(Test.email == email)
        ...     result = await self.session.execute(stmt)
        ...     return result.scalar_one_or_none()
    """
    
    def __init__(self, session: AsyncSession):
        """
        Initialize the repository with Container-injected AsyncSession.
        
        Args:
            session: AsyncSession for database operations (injected via Container)
        """
        super().__init__(session, Test)
    
    # TODO: Add custom query methods here
    # Example:
    # async def find_by_email(self, email: str) -> Test | None:
    #     """Find test by email address using native session."""
    #     stmt = select(Test).where(Test.email == email)
    #     result = await self.session.execute(stmt)
    #     return result.scalar_one_or_none()
    