"""
test Command (Generated by ftf make:command)

This is a custom CLI command that extends the ftf CLI with domain-specific
functionality.

Usage:
    ftf test [OPTIONS]

Educational Note:
    Custom commands allow you to add project-specific tooling to the ftf CLI.
    This is useful for:
    - Deployment scripts
    - Database maintenance
    - Data migrations
    - Report generation
    - Custom automation

    Unlike Laravel (which has command auto-discovery via namespaces),
    you need to manually register this command in src/ftf/cli/main.py.

Registration:
    Add this to src/ftf/cli/main.py:

    from ftf.cli.commands.test import app as test_app
    app.add_typer(test_app, name="test")

Comparison with Laravel:
    Laravel (Artisan):
        php artisan make:command DeployCommand
        // Auto-registered via $commands property in Kernel.php

    Fast Track:
        ftf make:command deploy
        // Manual registration in main.py (for now)
"""

import typer
from rich.console import Console

# Create command group
app = typer.Typer()
console = Console()


@app.command()
def main(
    option: str = typer.Option(None, "--option", "-o", help="Example option"),
    flag: bool = typer.Option(False, "--flag", "-f", help="Example flag"),
) -> None:
    """
    test command - Add description here.

    This command performs [describe what it does here].

    Args:
        option: Example option parameter
        flag: Example boolean flag

    Example:
        $ ftf test --option value
        $ ftf test --flag
    """
    console.print(f"[bold cyan]Running test command...[/bold cyan]")

    # TODO: Implement your command logic here
    if option:
        console.print(f"[green]Option value:[/green] {option}")

    if flag:
        console.print("[green]Flag is enabled[/green]")

    # Example: Execute operations
    try:
        # Add your command logic here
        console.print("[green]✓ Command completed successfully![/green]")
    except Exception as e:
        console.print(f"[red]✗ Error: {e}[/red]")
        raise typer.Exit(code=1)


# Optional: Add subcommands
# @app.command("subcommand")
# def subcommand():
#     """Subcommand description."""
#     console.print("Subcommand executed")
