"""
TestEmail Mailable

This module defines an email mailable for sending test emails.
Generated by Fast Track Framework CLI.
"""

from ftf.mail import Mailable


class TestEmail(Mailable):
    """
    TestEmail mailable.

    This mailable is responsible for composing and sending test emails.
    It uses the Builder Pattern for fluent email composition.

    Attributes:
        # TODO: Add mailable attributes here (e.g., user, order, etc.)

    Example Usage:
        ```python
        from mail.test_email import TestEmail
        from ftf.mail import Mail

        # Send immediately
        await Mail.send(TestEmail(...))

        # Fluent API with recipients
        await Mail.to("user@example.com", "John Doe").send(TestEmail(...))

        # Queue for background processing
        await Mail.to("user@example.com").queue(TestEmail(...))
        ```

    Educational Note:
        Mailables separate email composition from delivery. This provides:
        - Testability: Easy to test email content without sending
        - Reusability: Same mailable can be sent to different recipients
        - Maintainability: Email logic is centralized
    """

    def __init__(self) -> None:
        """
        Initialize mailable.

        Args:
            # TODO: Add constructor parameters (e.g., user: User)
        """
        super().__init__()

        # TODO: Store constructor parameters as instance variables
        # Example:
        # self.user = user

    async def build(self) -> None:
        """
        Build email content.

        This method defines the email structure using fluent builder methods:
        - subject(): Set email subject
        - from_(): Set sender address
        - view(): Use Jinja2 template
        - text(): Set plain text body
        - html(): Set HTML body
        - attach(): Add file attachment

        Example:
            ```python
            async def build(self) -> None:
                self.subject("Welcome to Our App!")
                self.from_("noreply@example.com", "My App")
                self.view("mail.welcome", {"user": self.user})
            ```

        Note:
            This is called automatically when the email is sent.
            You don't need to call it directly.
        """
        # TODO: Implement email composition
        # Example with template:
        # self.subject("Your subject here")
        # self.from_("noreply@example.com", "My App")
        # self.view("mail.template_name", {"variable": "value"})

        # Example with plain text:
        # self.subject("Your subject here")
        # self.from_("noreply@example.com", "My App")
        # self.text("Plain text email content")

        # Example with HTML:
        # self.subject("Your subject here")
        # self.from_("noreply@example.com", "My App")
        # self.html("<h1>HTML email content</h1>")

        # Example with attachment:
        # self.subject("Your subject here")
        # self.from_("noreply@example.com", "My App")
        # self.view("mail.invoice", {"invoice": self.invoice})
        # self.attach("/path/to/file.pdf", "invoice.pdf", "application/pdf")

        self.subject("TODO: Set your email subject")
        self.from_("noreply@example.com", "My App")
        self.text("TODO: Set your email content")
